### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by naonao-a** [Diudiu-wl/sumikko#2]
提一个小小建议,可以有个选择让他们是否保持在窗口的最前端,不论我最后新打开哪个页面,它都在最上层

**Comment by Diudiu-wl** [comment]
> 提一个小小建议,可以有个选择让他们是否保持在窗口的最前端,不论我最后新打开哪个页面,它都在最上层

感谢建议，现在更新了始终在最上层，欢迎查收❤

**Comment by naonao-a** [comment]
> > 提一个小小建议,可以有个选择让他们是否保持在窗口的最前端,不论我最后新打开哪个页面,它都在最上层
> 
> 感谢建议，现在更新了始终在最上层，欢迎查收❤

好快呀,谢谢博主,这个超可爱
